# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: scheduler-fp
version: '0.0.0'
github: "goosetherumfoodle/scheduler-fp"
license: MIT
author: "Jesse Hanley"
maintainer: "Jesse Hanley"
# synopsis: A new Haskeleton package.
# description: scheduler-fp is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - google-oauth2-jwt
  - wreq
  - text
  - bytestring
  - lens
  - aeson
  - lens-aeson
#  - lens-tutorial
  - containers
  - load-env
  - hourglass
  - vector
  - parsec
  source-dirs: library

executables:
  scheduler-fp:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - scheduler-fp
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  scheduler-fp-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - scheduler-fp
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  scheduler-fp-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - scheduler-fp
    - tasty
    - tasty-hspec
    - aeson
    - raw-strings-qq
    - yaml
    - hourglass
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
