# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: scheduler-fp
version: '0.0.0'
github: "goosetherumfoodle/scheduler-fp"
license: AGPL-3
author: "Jesse Hanley"
maintainer: "Jesse Hanley"
# synopsis: A new Haskeleton package.
# description: scheduler-fp is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - cookie
  - google-oauth2-jwt
  - wreq
  - text
  - bytestring
  - lens
  - aeson
  - lens-aeson
#  - lens-tutorial
  - containers
  - unordered-containers
  - load-env
  - http-types
  - hourglass
  - vector
  - parsec
  - twilio
  - yaml
  - prettyprinter
  - formatting
  - uri-encode
  - servant-server
  - servant-xml
  - xmlbf
  - wai-logger
  - wai
  - warp
  - http-api-data
  source-dirs: library

executables:
  server:
    source-dirs: executable
    main: MainServer.hs
    dependencies:
    - base
    - scheduler-fp
    ghc-options:
    - -main-is MainServer
    - -split-objs
    - -O2
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

  alert-nag:
    source-dirs: executable
    main: Alert/Nag.hs
    dependencies:
    - base
    - scheduler-fp
    ghc-options:
    - -main-is Alert.Nag
    - -split-objs
    - -O2
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

  alert-emergency:
    source-dirs: executable
    main: Alert/Emergency.hs
    dependencies:
    - base
    - scheduler-fp
    ghc-options:
    - -main-is Alert.Emergency
    - -split-objs
    - -O2
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

  alert-week:
    source-dirs: executable
    main: Alert/Week.hs
    dependencies:
    - base
    - scheduler-fp
    ghc-options:
    - -main-is Alert.Week
    - -split-objs
    - -O2
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  scheduler-fp-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - scheduler-fp
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  scheduler-fp-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - scheduler-fp
    - tasty
    - tasty-hspec
    - aeson
    - raw-strings-qq
    - yaml
    - hourglass
    - text
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
